config/routes.rb
Rails.application.routes.draw do
  get 'access/login'

  get 'access/attempt_login'

  get 'photos/new'

  get 'photos/create'

  get 'photos/index'

  resources :photos, only: [:new, :create, :index, :destroy]

  root "photos#index"

  match ':controller(/:action(/:id))', :via => [:get, :post]

end

app/models/photo.rb
class Photo < ActiveRecord::Base
	has_attached_file :image ,
                    :url => "/file/:id/:style_:basename.:extension",
                  styles: { thumb: ["64x64#", :jpg]}
	validates_attachment :image,
                     content_type: { content_type: ["image/jpeg", "image/gif", "image/png", "video/mp4", "video/avi"] }

    # has_attached_file :image,
    #               styles: { thumb: ["64x64#", :jpg] }
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password

end

app/controllers/access_controller.rb
class AccessController < ApplicationController

  after_filter :allow_iframe, only: :my_embeddable_widget

  def my_embeddable_widget
    render
  end
  
  def login
  end

  def attempt_login

   	if params[:username].present? && params[:password].present?
   		user_logged_in = User.where(:login => params[:username]).first
      @user_id = user_logged_in.id
      current_user = User.find_by_sql("select firstname from users where id = #{user_logged_in.id};")
      current_user_name = (current_user[0].firstname).to_s
      redirect_to(:controller => "photos",:action => 'index', :user=>current_user_name)



   	end

   end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

	#layout false

  def new
  	@photo = Photo.new
  end

  def create
  	@photo = Photo.new(photo_params)
    @name = @photo.author
    count = Photo.find_by_sql("SELECT MAX(id) FROM Photos")
    
    id = User.find_by_sql("select id from users where login='#{@name}'")
    if id.any?
  	if @photo.save
  		flash[:success] = "The photo was added! Your video id is #{@photo.id}." 
      #flash[:success] = "asdlkfjlasdfjs"
  		redirect_to action: 'project_content', id: @photo.id
  	else
  		render 'new'
    end
    else

      flash[:success] = "Please enter the SPC Login Name!" # red notice to be implemented
      render 'new'
      end
  end

  def index

  	@photos = Photo.order('created_at')

  end

  def project_content
    @photo = Photo.find(params[:id])

    @videos = Photo.find_by_sql("select * from photos where author ='#{params[:username]}' and id <> #{params[:id]}")



  end

  private

  def photo_params
    #user_id_1 = 6


    params.require(:photo).permit(:image, :projectname, :title, :author)
  end



end

app/helpers/access_helper.rb
module AccessHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/access/login.html.erb
<% @page_title = "Login Page" %>

 
  <%= form_tag(:controller=> 'access',:action => 'attempt_login') do %>
  <form class="form-horizontal">
  <div class="form-group">
      <%= label_tag(:username, 'Username', :class => "col-sm-2 control-label") %>
      <div class="col-sm-10">
      <%= text_field_tag(:username, nil , {:class => "form-control"}) %>
      </div>
      </div>

    
    <div class="form-group">
      <%= label_tag(:password, 'Password', {:class => "col-sm-2 control-label"}) %>
      <div class="col-sm-10">
      <%= password_field_tag(:password, nil ,{:class => "form-control"}) %>
      </div>
      </div>
    <!-- <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <div class="checkbox">
        <label>
          <input type="checkbox"> Remember me
        </label>
      </div>
    </div>
  </div> -->
  <br />
  <br />
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">  
    <br />
  <%= submit_tag("Sign In") %>
  </div>
  </div>

  
  </form>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SimpleUploader</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'swfobject' %>
  <%= csrf_meta_tags %>
</head>
<body>

<!-- <nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <%= link_to 'Simple Uploader', root_path, class: 'navbar-brand' %>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Photos', root_path %></li>
        <li><%= link_to 'Upload Your Photo', new_photo_path %></li>
      </ul>
    </div>
  </div>
</nav> -->

<div class="container">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>">
      <%= value %>
    </div>
  <% end %>

  <%= yield %>
</div>

</body>
</html>

app/views/photos/_photo.html.erb
<div class="media">
  <div class="media-left">
    <%#= link_to image_tag(photo.image.url, class: 'media-object'), photo.image.url, target: '_blank' %>
    <%= link_to image_tag(photo.image.url(:thumb), class: 'media-object'),{:action => 'project_content', :id => photo.id,:username=>photo.author} %>
    <%#= video_player({:file => photo.image.url}) %>
  </div>
  <div class="media-body">
    <h4 class="media-heading"><%= photo.title%></h4>
  </div>
</div>

app/views/photos/create.html.erb
<h1>Photos#create</h1>
<p>Find me in app/views/photos/create.html.erb</p>

app/views/photos/index.html.erb
<div class="identity">Logged in as:<%#= params[:user]%>
  <%#= @user_id%>
</div>
<div class="page-header"><h1>Photos</h1></div>
<%="Check"%>
<%#= render @photos %>

app/views/photos/new.html.erb
<div class="page-header"><h1>Upload Video</h1>
<%# link_to 'Upload Your Photo', new_photo_path %>
</div>


<%= form_for @photo do |f| %>
 

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
     <br />
    <%#= f.label :project, "Project Name" %>
    <%#= f.text_field :projectname, class: 'form-control' %>
    
    
    <%= f.label :author %>
    <p class="bg-success">
    <%= "Please Enter Your SPC Login Name:  " %>
    </p>
    <%= f.text_field :author, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: 'form-control'  %>
  </div>
   <br />

  <%= f.submit 'Upload', class: 'btn btn-primary' %>
<% end %>

app/views/photos/project_content.html.erb
<%#= image_tag @photo.image.url.to_s, :class => "img-thumbnail" , size: "360" %>
<!-- <div>
 <p class="bg-success"> The photo was added! Your video id is <mark><%= @photo.id   %></mark>. Please update the video id in the details. </p>
 </div> -->
<%= video_player({:file => @photo.image.url}, width: 980, height: 580) %>
<br/>
<br/>

<!-- <div class="col-xs-6">

<h3 class="text-warning">
<%= "Other Videos Uploaded By #{@photo.author}"  %>
</h3>
</div>
<br/>

<br/>
<br/>
<%@videos.each do |v|%>


<%= link_to image_tag(v.image.url(:thumb), class: 'col-md-1 img-circle' ),{:action => 'project_content', :projectname => v.projectname,:username=>v.author} %>
<%end%> -->

app/views/shared/_error.html.erb
<% if object.errors.any? %>
  <div class="panel panel-warning errors">
    <div class="panel-heading">
      <h5><i class="glyphicon glyphicon-exclamation-sign"></i> Found errors while saving</h5>
    </div>

    <ul class="panel-body">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>